/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { City } from './city';
import { DeliveryType } from './deliveryType';
import { Shop } from './shop';
import { User } from './user';


export interface Proposal {
    deliveryTypes?: Array<DeliveryType>;
    description?: string;
    fromCityId?: number;
    fromcity?: City;
    id?: number;
    idUser?: number;
    name?: string;
    price?: string;
    shops?: Array<Shop>;
    status?: boolean;
    toCityId?: number;
    tocity?: City;
    user?: User;
}
